### ISSUE TITLE
args.logdir parameter is obsolete but still in docs

### ISSUE THREAD

**Issue by robander** [dita-ot/docs#127]
See https://github.com/dita-ot/dita-ot/issues/2579, in particular @jelovirt 's comment:

> args.logdir is an obsolete argument. It should be removed in 2.5 or 2.4.3.

It's still in our docs as a valid parameter:
view-source:http://www.dita-ot.org/dev/parameters/parameters-base.html#base__args.logdir

Guessing we should at least update the docs to mark it obsolete, until such time as it's actually removed from the code?

**Comment by infotexture** [comment]
@robander 👍 Makes sense to push a note to the parameter description in the docs.

That would be most helpful if we provide guidance on the preferred logging method(s) to use instead.

For builds with the `dita` command, I assume that's `dita --logfile=<file>`, but what's the recommended alternative for Ant builds — just `ant -l <file>`?

If I'm reading the comments by @shaneataylor in dita-ot/dita-ot#2579 correctly, it looks like the log file would need to be specified with an absolute path to control the location, otherwise it lands in the input directory, right? 

_(IIRC, `ant -logger org.dita.dost.log.DITAOTBuildLogger` is also no longer recommended.)_

**Comment by robander** [comment]
For Ant builds, I think that `ant -l <file>` is probably the recommendation, yes.

I tried specifying that parameter with a relative value, and it worked fine:
```
C:\DITA-OT\dita-ot-2.4.3>bin\ant -f build.xml -Dargs.input=docsrc\samples\hierarchy.ditamap -Dtranstype=xhtml -l test\log.txt
Buildfile: C:\DITA-OT\dita-ot-2.4.3\build.xml

C:\DITA-OT\dita-ot-2.4.3>dir test\log.txt

 Directory of C:\DITA-OT\dita-ot-2.4.3\test
02/01/2017  12:07 PM            28,186 log.txt
               1 File(s)         28,186 bytes
               0 Dir(s)  277,670,686,720 bytes free

C:\DITA-OT\dita-ot-2.4.3>
```
