### ISSUE TITLE
Description of HTML5 parameters is not equal to the HTML-based output parameter description

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#132]
The following parameters are explained on [HTML-based output parameters](http://www.dita-ot.org/2.4/parameters/parameters-base-html.html) and also on [HTML5 parameters](http://www.dita-ot.org/2.4/parameters/parameters-html5.html).

* args.artlbl
* args.copycss
* args.css
* args.csspath
* args.cssroot
* args.dita.locale
* args.ftr
* args.gen.default.meta
* args.hdf
* args.hdr
* args.hide.parent.link
* args.indexshow
* args.outext
* args.xsl

If possible, the descriptions should be equal/reused or simply removed from the HTML5 page, because they are not specific to HTML5. For example, compare the `args.hdf` description. If you like, explain how you want this to be handled and I'd send a PR.

**Comment by infotexture** [comment]
This is a side-effect of the de-coupling of the HTML5 plug-in for version 2.4. As the [Release Notes](http://www.dita-ot.org/2.4/release-notes/) say:

> In release 2.4, all dependencies between HTML5 and XHTML have been removed to ensure that HTML5 processing can be further refactored in the future without affecting XHTML output, or other HTML-based transformations such as eclipsehelp, htmlhelp or javahelp.

Whereas in 2.3, the listings for [HTML5 and XHTML parameters](http://www.dita-ot.org/2.3/parameters/parameters-common-html.html) and [HTML5](http://www.dita-ot.org/2.3/parameters/parameters-html5.html) contained only specific parameters _(not shared with with the base HTML transform)_, the new HTML5 architecture actually duplicates these parameters.

The conref push mechanism is used to extend the descriptions in the base HTML parameter listing, but since the augmented descriptions are only pushed to a single location, the duplicates in the HTML5 topic do not currently benefit from the editorial improvements.

The re-use mechanism should be re-evaluated to either push the extended descriptions to the HTML5 topic too, or exclude the duplicate parameters from the autogenerated listing for HTML5.
