### ISSUE TITLE
Example of multiple ditavals referenced from the command line

### ISSUE THREAD

**Issue by StanDoherty** [dita-ot/docs#154]
Wow . . . I would love to specify multiple DITAVAL rules files on the dita command line.

None of the following best-guesses at how the "system separator character" might work on the command line seem to work.

c:\dita-ot\bin\dita -i mapgen_multiple-ditavals.ditamap -f html5 -o xoutput\html5 
-filter ditaval\blue_ditaval.ditaval ditaval\red_ditaval.ditaval  
-filter ditaval\blue_ditaval.ditaval;ditaval\red_ditaval.ditaval  
-filter ditaval\blue_ditaval.ditaval:ditaval\red_ditaval.ditaval  
-filter ditaval\blue_ditaval.ditaval,ditaval\red_ditaval.ditaval  

Is this feature available only in ant? Have working example (any platform)?

Thanx
Stan

**Comment by StanDoherty** [comment]
[src_multiple-ditavals.zip](https://github.com/dita-ot/docs/files/1346815/src_multiple-ditavals.zip)

**Comment by robander** [comment]
Hmm ... the semi-colon should work on Windows, and colon on Mac/Linux. I'm guessing you're on Windows because the sample uses a backslash, so it should work with
`-filter ditaval\blue_ditaval.ditaval;ditaval\red_ditaval.ditaval`

You may be better off using absolute paths for each of them though --
`-filter c:\some\path\ditaval\blue_ditaval.ditaval;c:\some\path\ditaval\red_ditaval.ditaval`

Only other suggestion is that this feature was added in the latest release (2.5) so if you're on anything older than that, it will not work.

**Comment by StanDoherty** [comment]
Hi Robert -- 

Thanks for the response. I am actually using 2.5.3 for this testing. 

When I run the following command using the semicolon:

c:\dita-ot_psi11\bin\dita -i mapgen_multiple-ditavals.ditamap -f html5 -o xoutput\html5 -filter ditaval\blue_ditaval.ditaval;ditaval\red_ditaval.ditaval

I receive the following error message.

Error: Target "ditaval\red_ditaval.ditaval" does not exist in the project "DOST".

It always objects the the last DITAVAL in the sequence. 

I get the same sort of error message when I supply absolute paths to the DITAVAL files.. 

Error: Target "c:\dita-ot_source\src_multiple-ditavals\ditaval\red_ditaval.ditaval" does not exist in the project "DOST".

Stan

**Comment by infotexture** [comment]
43542c9 updates docs to include explicit examples of platform-specific path separator characters in more places.

Tested 2.5.4 code on macOS, `--filter=samples/filters/red.ditaval:samples/filters/green.ditaval` works.
