### ISSUE TITLE
Drop "History of the PDF transformation"

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/docs#167]
Is this actually needed/useful any more?

**Comment by infotexture** [comment]
IIRC, this content was originally developed by @keberlein to provide context for the somewhat confusing `pdf2` name and other oddities.

The explanation is certainly helpful for those who've wondered about these things, but I'm not sure how many new users are really interested in the arcane backstory.

I would be OK with dropping the topic or demoting it into a _Reference_ section if that helps to sharpen the focus on topics of more immediate utility.

**Comment by infotexture** [comment]
FWIW, I was curious and dug into the analytics data: it looks like this page has been viewed only 37 times since its creation in April of 2016, which amounts to ~0.02 % of our total traffic.

For context, the parent [Customizing PDF output](http://www.dita-ot.org/dev/dev_ref/pdf-customization.html) page is one of our top 10 pages, with ~4000 page views in the same time frame, so it looks like even users that are nearby may not be as interested in this topic.

**Comment by robander** [comment]
👍 to demoting to Reference. Since we don't have a "Dark dark history of DITA-OT" section...

**Comment by infotexture** [comment]
Moved to _Reference_ for 3.0.
