### ISSUE TITLE
Missing defaults for 'args.rellinks'

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#171]
The common parameters do not reveal the default value of `args.rellinks`.

**Common parameters**

```
args.rellinks
    Specifies which links to include in the output. The following values are supported:

        none – No links are included.
        all – All links are included.
        noparent – Parent links are not included.
        nofamily – Parent, child, next, and previous links are not included.
```

The default value is `nofamily` for `pdf2`.

**org.dita.pdf2/build.xml**

```xml
<condition property="args.rellinks" value="nofamily">
  <not><isset property="args.rellinks"/></not>
</condition>
```

The default value for other plugins is `all`.

**org.dita.base/build_init.xml**

```xml
<condition property="include.rellinks" value="#default parent child sibling friend next previous cousin ancestor descendant sample external other">
  <or>
    <equals arg1="${args.rellinks}" arg2="all"/>
    <not><isset property="args.rellinks"/></not>
  </or>
</condition>
```

**Comment by infotexture** [comment]
Default values should normally be extracted from plug-in source when the topics are generated, not sure why that's failing here. 

May be related to `pdf`/`pdf2` aliasing, or because other transtypes have different defaults. 

(It's one of the [Common parameters](http://www.dita-ot.org/dev/parameters/parameters-base.html), so not really PDF-specific.)

Will investigate.
