### ISSUE TITLE
DuckDuckGo Search is broken

### ISSUE THREAD

**Issue by lief-erickson** [dita-ot/docs#188]
When I use the Search box to look content I notice two things, both of which are problems in my mind.

1. The search results are not from the current release. Instead results are from "dev/dev_ref." My expectation would be that the current release's documentation would be searched. Ideally, if we wanted to search an older version or the develop files there would be a way to do so (without needing to know the URL structure and amending the DuckDuckGo search with it).

2. Most search results are leading to 404 pages. I wanted to find information about 'preprocess2' and 'map-first preprocessing.' These are terms from the Release Notes, but no links in the Release Notes to the corresponding topics; ergo, search. 

For instance, this is the result for 'preprocess2':
https://duckduckgo.com/?sites=dita-ot.org%2Fdev&ka=h&k7=%23fafafa&kj=%233f3f3f&ky=%23fafafa&kx=b&kt=Helvetica&kh=1&q=preprocess2&ia=web

The first result is the one I think I want. This is the link:
http://www.dita-ot.org/dev/dev_ref/map-first-preprocessing.html

But I know I want to search the 3.0 docs, so I change the DuckDuckGo search to use 3.0 and this is the result:
http://www.dita-ot.org/3.0/dev_ref/map-first-preprocessing.html

The actual page that I want is this one:
http://www.dita-ot.org/3.0/reference/map-first-preprocessing.html

This doesn't feel like an issue with the docs at all, but a configuration issue with DuckDuckGo. Perhaps it can be flushed of its memory and relearn the new directory structure?

**Comment by infotexture** [comment]
Thanks for pointing this out, but nothing's really broken here: DuckDuckGo's search index just hasn't caught up to the source file refactoring performed for v3.0.1 with #185.

Those changes were pushed roughly 48h ago, so the crawlers may take a few more days to notice the revised file structure and update their indexes accordingly.

(We have redirects in place for the most frequently shared topics per https://github.com/dita-ot/dita-ot.github.io/issues/43, so the long-term impact should be minimal.)

The choice to point search to the `dev` docs rather than the latest release was deliberate, as these typically include all content from the latest release, plus unreleased bugfixes and new content, so they're generally the best resource for anyone interested in the latest docs. Pointing search to the `dev` docs also means we don't need to reconfigure the search engine for each release.

### Workaround: Press ”**t**” to find topics by title

You can filter the list of topics with the topic finder that appears when you type the letter ”t“. If you enter a search term like “preprocess” or “map-first”, you'll see the topics that contain these terms in the title.

_Hope that helps until DuckDuckGo catches up…_
