### ISSUE TITLE
Explain font configuration

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#192]
The topic [The configuration.properties file](http://www.dita-ot.org/dev/parameters/lib-configuration-properties.html#ariaid-title1) links to Jarnos blog post [Font configuration in PDF2](http://www.elovirta.com/2016/02/18/font-configuration-in-pdf2.html). It would be nice, if the information from this post would be migrated to a docs topic.

Further on, the explanation of **[PDFX008W](http://www.dita-ot.org/dev/topics/DITA-messages.html#msgs__title)** should link to this topic.

**Comment by infotexture** [comment]
The original post suggests the following:

> this is something that will probably change in DITA-OT 3.0. The font mapping process code will still be available, but will not be enabled by default.

To my knowledge, this wasn't changed in 3.0, so I'm not sure whether we should canonize this approach yet as best practice in the docs, or leave it as an external link for reference.

@jelovirt, @robander Any preferences?

**Comment by jelovirt** [comment]
The option I present in the blog is what I consider to be better, because it gives the stylesheet author direct access to font definitions and supports multiple languages. But it's not always better or Correct. Best option would be to describe _both_ as alternative strategies and just mention that the I18N processing is on by default.
