### ISSUE TITLE
Problems when searching in documentation

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#217]
Let's say I open this link:

http://www.dita-ot.org/dev/

and then search in the right top search field for "strings", then press ENTER.
I would have expected (probably based on my experience with Google search) to be presented with a list of possible results but instead I'm taken probably to the first match but the match is not highlighted.

**Comment by lief-erickson** [comment]
@raducoravu, I gave your post a "thumbs-up" reaction two years ago, because I agreed with you then. I still agree with you. Google has trained me well.

However, over the course of my thesis project working with the DITA-OT docs, including where I specifically investigated the search capabilities and limitations of the site, I learned more. The Algolia DocSearch used on the site does not have a search engine results page (SERP) like you get when doing a search with Google. Instead, there is a drop down list showing matches. The length of that list is configurable. It is currently set to 10. The default was 5, but I felt that was too few, especially given that there is no SERP and @infotexture agreed to increase it. That list will show the page title and the headline or a small portion of text around the highlighted search term. That is all of the context that the Algolia DocSearch tool allows. Unfortunately, DocSearch does not allow pagination of the results. Pagination could allow a much greater number of results and be helpful in cases where many pages have matching terms but due to weighting the results isn't in the top 10. 

(Aside: the drop down list that Algolia uses _is_ beneficial in some cases. For instance, it can significantly increase the time from search to answer, especially if the answer is found directly in the drop down list so that the user doesn't even need to click through. If the user does need to click through, they needn't first go to a SERP, which slows the process down...in some cases.)

You also mentioned highlighting. The highlighting does occur, but only in the search results drop down. Unfortunately, there is no highlighting when clicking through to the page. Again, Algolia DocSearch does not allow for this.

A different search tool would likely allow for both a SERP and on-page highlighting, but it's unlikely that the team will be looking into a replacement anytime soon.

**Comment by raducoravu** [comment]
@lief-erickson what can I say? I think I got used to the current search, I need to be careful not to press ENTER (which takes me to the first match) but instead keep adding keywords until I see the match which interests me in the presented list.

**Comment by infotexture** [comment]
Closing per discussion in [2020-08-13 contributors call](https://github.com/dita-ot/dita-ot/wiki/Meeting-minutes-2020-08-13).
