### ISSUE TITLE
Add links to DITA OT Day videos

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#218]
Maybe for some of the topics in the documentation there could be some relevant past DITA OT Day presentations which could be linked to.

**Comment by lief-erickson** [comment]
For (easy) reference:
https://www.oxygenxml.com/events/2017/dita-ot_day.html
https://www.oxygenxml.com/events/2016/dita-ot_day.html
https://www.oxygenxml.com/events/2015/dita-ot_day.html
https://www.oxygenxml.com/events/2014/dita-ot_day.html

**Comment by lief-erickson** [comment]
@raducoravu, are the links in the banner on the website what you were thinking? If so, it looks like @infotexture did that with [PR #215](https://github.com/dita-ot/website/pull/215) from the website repo. I'd say this issue is complete and can be closed. 

If you're intention was to have specific topics have links to particular videos, then we'd probably want a list of suggestions.

**Comment by raducoravu** [comment]
I kind of wished for some related links between certain documentation topics and video links.

**Comment by infotexture** [comment]
🎥 Implemented by @lief-erickson for 3.5.4 in #304.

**Comment by raducoravu** [comment]
Thanks for the hard work @lief-erickson and for the review @infotexture, I'm glad the videos are now available in the DITA OT docs:
https://www.dita-ot.org/3.5/topics/dita-ot-day-videos.html
I hope others will find them useful as well. 6 years of meetups, we had a good run :)
