### ISSUE TITLE
Consider documenting hidden parameters like "include.rellinks"

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#22]
Based on: https://github.com/dita-ot/dita-ot/issues/1887

The official parameter for controlling related links generation is "args.rellinks". But some people who publish output might want a more precise way of controlling the generated links by setting directly the parameter "include.rellinks" which specifies in clear what types of links are allowed for generation.

**Comment by infotexture** [comment]
A dedicated topic for this parameter is in the docs _(since v1.7?)_, but somewhat hidden in the _Developer Reference_: see http://www.dita-ot.org/2.0/dev_ref/ant-properties.html.

For v2.1, the topic appears alongside the other parameter descriptions in the _Parameter Reference_: see http://www.dita-ot.org/2.1/parameters/internal-ant-properties.html.

**Comment by infotexture** [comment]
The source file contains an XML comment with what appears to be an earlier autogenerated list of  parameters: https://github.com/dita-ot/docs/blob/3fe3fea/parameters/internal-ant-properties.dita#L31.

Documentation for most of these are now generated automatically since #30, but we could consider exposing the remaining hidden parameters as well.

Not sure how much effort this would require, nor how useful the full list would be to users.

@robander @jelovirt — Opinions?

**Comment by jelovirt** [comment]
I think I've compiled that list with just grepping the Ant code. It's not complete and is probably hideously out of date. We could document all of those, but then someone would need to update the documentation every time a new internal property is added or removed. I think internal properties in Ant should not be document outside the actual code.

**Comment by infotexture** [comment]
OK, I'll close this & remove the outdated comment then.
