### ISSUE TITLE
Fix output dir produced by --propertyfile=file example

### ISSUE THREAD

**Issue by osg** [dita-ot/docs#265]
## Expected Behavior
I expected the output from this example to be in `.../samples/output/sequence/`.

## Actual Behavior
The `index.html` file is in the correct location, but the referenced topics are created in `.../samples/output/sequence/docsrc/samples/`.

## Steps to Reproduce

1. Go to `...dita-ot-3.3.4/docsrc`.
2. Run $ `dita --input=sequence.ditamap --format=html5 --output=output/sequence --args.input.dir=. --propertyfile=properties/sequence-html5.properties`
3. Explore. :)

## Environment

* DITA-OT version: 3.3.4
* Operating system and version: Linux Ubuntu 19.04
* How did you run DITA-OT? `dita` command
* Transformation type: HTML5

**Comment by infotexture** [comment]
Based on `--propertyfile` example in https://www.dita-ot.org/dev/topics/build-using-dita-command.html.

With the command syntax above, relative paths from `index.html` to topic files are not generated correctly.

Either the underlying toolkit behavior has changed since this example was created, or the specification of `args.input.dir` using the `.` shorthand for the current directory (`samples`) instead of the absolute path changes the location of the generated topics without adjusting the links in the `index.html` file accordingly.

**Comment by infotexture** [comment]
### Confirmed in local testing

✅ Running from `docsrc/samples`, this generates correct output with all internal paths to topics and custom CSS intact:

```bash
dita --input=sequence.ditamap --format=html5 \
     --output=output/sequence \
     --args.input.dir=/absolute/path/to/dita-ot-dir/docsrc/samples \
     --propertyfile=properties/sequence-html5.properties
```

#### Output

```bash
samples/output/sequence/
├── branding/
├── concepts/
├── image/
├── index.html
└── tasks/
```

💥 However, substituting the absolute path to `docsrc/samples` _(which **is** the current directory)_ with the current directory shorthand `.` yields **different** results:

```bash
dita --input=sequence.ditamap --format=html5 \
     --output=output/sequence \
     --args.input.dir=. \
     --propertyfile=properties/sequence-html5.properties
```

#### Output

```bash
samples/output/sequence/
├── branding/
│   ├── commonltr.css
│   └── commonrtl.css
├── docsrc/
│   └── samples/
│       ├── concepts/
│       ├── image/
│       └── tasks/
└── index.html
```

⚠️ In this case, the relative paths to topic files in `index.html` are not adjusted to reflect the _(incorrect)_ output folder hierarchy, which erroneously inserts the `docsrc/samples` part of the input path into the output folder hierarchy.

Also, the [custom CSS](https://github.com/dita-ot/docs/blob/develop/samples/css/style.css) file [defined in the properties file](https://github.com/dita-ot/docs/blob/develop/samples/properties/sequence-html5.properties#L5) via `args.cssroot = ${args.input.dir}/css/` is neither copied to output nor referenced in HTML file `<head>` elements.

If the input directory parameter is omitted from the command _(which would seem to make sense, since the current directory is clear)_, the generated folder hierarchy is correct, but the custom CSS file is neither copied to output nor referenced.

@jelovirt @robander Should the current directory shorthand `.` work in this context _(i.e. is this a toolkit bug?)_, or should we just update the example in the docs to clarify that `args.input.dir` **must** be specified with an absolute path in this case.

**Comment by osg** [comment]
@infotexture will an absolute path work in the context of a build system where the command is run on some other server somewhere where I am not a user?

**Comment by infotexture** [comment]
@osg No, absolute paths are not portable, as the directory structure may differ if the same project is built on a CI server or a different computer.

Certain parameters currently require absolute paths, and there are several open issues to align this, including dita-ot/dita-ot#2815 & dita-ot/dita-ot#3016.

In the meantime, one workaround for macOS & Linux is to define such parameters in properties files using the `$PWD` shell variable, which expands to the absolute path of the current working directory. 

_For example:_

     --args.cssroot=$PWD/resources
