### ISSUE TITLE
Adding a <note> to the "Adding new diagnostic messages" topics explaining what needs to be done to show an <ouput-message> in the Oxygen Results view.

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#443]
Add a **`<note>`** to the [Adding new diagnostic messages](https://www.dita-ot.org/dev/topics/plugin-messages.html) topic explaining what needs to be done to show an **`<output-message>`** in the Oxygen `Results` view.

I tried the *Edit this page* button but I do not have to permissions to commit and add a pull request.

```xml
<note type="note">If you want the message to be shown in the Oxygen XML Results view, 
the <xmlatt>id</xmlatt> needs to start with the prefix <codeph>DOT</codeph>.
```

**Comment by infotexture** [comment]
> I tried the _Edit this page_ button but I do not have to permissions to commit and add a pull request.

@xephon2 That's odd. 🤔 

If you don't have push rights to the repo, [oXygen XML Web Author](https://www.oxygenxml.com/webauthor/) should prompt you to sign in to GitHub, fork the [dita-ot/docs](https://github.com/dita-ot/docs) repository (if you haven't already), and create the PR from your fork.

❓ @raducoravu: Has this workflow changed recently in the web author tool?

**Comment by infotexture** [comment]
As for the suggestion itself, I'm not sure we should mention oXygen here, as there's already a note that mentions the ID prefix convention:

> **Note:** By convention, the toolkit messages use `DOTX` but any sequence can be used by plug-in developers.

I suppose we _could_ extend that to mention that some tools may use this prefix when parsing logs. 

I've always thought of the `DOT*` prefixes as something reserved for the toolkit itself, and that messages from custom plug-ins would use their own prefixes and numbers, like `ACME123E`, so any company-specific parsers would pick these up.

@jelovirt @robander Any thoughts on this?

**Comment by raducoravu** [comment]
The "Edit this page" link which appears for each doc topic seems to work fine for me.
<img width="1218" alt="Screenshot 2022-12-05 at 08 26 37" src="https://user-images.githubusercontent.com/1005979/205564183-a3963cde-ba15-42b0-8d9f-c0cc1458d3d3.png">
About this request, I consider it to be a bug in Oxygen that it does not gather all message IDs, no matter what ID pattern they have, so this is not related to how the DITA OT works.

**Comment by robander** [comment]
> I've always thought of the `DOT*` prefixes as something reserved for the toolkit itself, and that messages from custom plug-ins would use their own prefixes and numbers, like `ACME123E`, so any company-specific parsers would pick these up.
> 
> @jelovirt @robander Any thoughts on this?

Agreed, I've used company-specific prefixes in all of my plugins.

**Comment by xephon2** [comment]
@raducoravu and @infotexture , this is how it looks on my private computer.
![grafik](https://user-images.githubusercontent.com/3266567/206571853-13ad42b6-c696-46a5-afe3-2afb7b7004ba.png)
![grafik](https://user-images.githubusercontent.com/3266567/206571543-9bd90351-34d9-48b4-adc5-cc62bba43eec.png)

**Comment by infotexture** [comment]
Thanks for the info in the comments above.

The last screenshot suggests something may be wrong with the step where oXygen selects the repo fork to submit the PR from, but I'll leave that for @xephon2 & @raducoravu to discuss separately.

**Comment by raducoravu** [comment]
I will ask my colleagues from the WebAuthor team to take a look at the screenshots @xephon2 pasted above. I also consider the DOT... message IDs should be "reserved" for the DITA OT and Oxygen should try to do a better job at gathering other message ID patterns as well.

**Comment by raducoravu** [comment]
We reproduced and added an internal issue for @xephon2 's problem of creating a pull request. He has an old fork of the dita ot docs project which is not up to date and this is possibly the cause.

**Comment by xephon2** [comment]
@raducoravu could you please define what "old" means? 100 days, 1000 commits? Let's say we're going to use this in our company environment and someone triggers a PR and the next one after half a year, then probably 5000 commits will be between the new and the previous PR. Would you consider this to be "old"?

**Comment by raducoravu** [comment]
@xephon2 I do not know. That's the simple answer. 
So we have this situation where there is a main GitHub repository like dita/dita-docs and someone does not have access rights to directly commit to it. That someone also has an old fork of the dita-docs in their account. When you attempt to edit and commit content from dita/dita-docs our WebAuthor will attempt to create a branch on that old fork "stefan/dita-docs" containing the latest changes that you made and also to possibly start a pull request.
We use some APIs to create the branch, sometimes the GitHub APIs fail without returning a proper error message (the GitHub APIs do not return very clear error messages from what I figured, probably not to help hackers exploit vulnerabilities). That's why you also receive that not helpful message not authorized exception. From what I tested it may happen that the API manages to create a branch even if the fork is a little bit stale (creating a branch worked for a fork which was about 3 commits behind than the main project) but it may fail to do so if the fork is very stale (creating a branch did not work if the fork was 300 commits behind the original repository). What I tried yesterday was that if creating a branch from the fork containing content from the original topic in the main repository failed to automatically synchronize your fork to the main repository (that "Sync fork" button which appears on each fork in the GitHub page, but called automatically) before creating the branch.

**Comment by raducoravu** [comment]
@xephon2 For completion we made some changes to the WebAuthor on our website, updated it to version 25.1, it should probably handle better such situations in which the fork of a project like the dita-docs is outdated and you attempt to create a commit and a pull request using it. But I cannot guarantee it will work in all cases.

**Comment by xephon2** [comment]
Thank you, Radu. This will help.



Stefan Jung
Head of Technical Documentation

Phone +49 (0)2572 879 279 Cell +49 (0) 172 8843770
***@***.***

Dometic Germany Holding GmbH - Betriebsstätte Emsdetten, Hollefeldstr. 63, 48282 Emsdetten, Nordrhein-Westfalen Germany

dometic.com<http://www.dometic.com>

<http://www.dometic.com>

[cid:Dometic_hori_sRGB-removebg-preview_7046ad0a-86d4-443e-abca-93a204245c21.png]

[http://dometicpressroomfrontend.qbank.se/deployedFiles/a5d04859b4034100c185cad8220074a0.png]<https://www.dometic.com/> [http://dometicpressroomfrontend.qbank.se/deployedFiles/d9c545300165a1ff85a9f729d21bf97b.png] <http://www.instagram.com/dometic>  [http://dometicpressroomfrontend.qbank.se/deployedFiles/f5b9430e2561a2e2233863b3a844eb66.png] <http://www.youtube.com/dometicofficial>

NOTICE: This email and any attachments are for the sole use of the intended recipient(s) and may contain confidential information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please notify the sender by reply email and destroy the original message.

DOMETIC GERMANY HOLDING GMBH

GESCHÄFTSFÜHRER:        SITZ DER GESELLSCHAFT:  AMTSGERICHT SIEGEN:
JAN KUJAW
        SIEGEN  HRB 5557
