### ISSUE TITLE
Troubleshooting builds

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/docs#56]
I think we need a set of topics helping users understand how to use the logs to identify and troubleshoot build problems. This should follow the tutorial approach outlined in https://github.com/dita-ot/docs/issues/37.

**Comment by infotexture** [comment]
:+1: Makes sense to extend the existing [Troubleshooting](http://www.dita-ot.org/dev/user-guide/troubleshooting-overview.html) content with additional information.

**Comment by keberlein** [comment]
The existing Troubleshooting content is pretty old. It was reorged slightly in 2009, and updated a few times since, but no significant content has been added for a LONG time. I have a list of problems that I (and my clients, some of them not technically sophisticated) have run into over the past six months; I'd be happy to share them. I suggest that we use the DITA 1.3 troubleshooting topic.

**Comment by keberlein** [comment]
This might be a good area of documentation to focus on for the next couple of milestones. It might help our extended group get moving if we had a common focus.

**Comment by infotexture** [comment]
@keberlein That list would be welcome, feel free to include here.

We could draft an outline for the section in this issue thread, people could send pull requests with input for individual topics later. 

DITA 1.3 troubleshooting topic makes sense.

**Comment by keberlein** [comment]
@infotexture Here are some common problems:
- Build.xml not found (a writer has moved the DITA-OT and failed to update the transformation scenario.)
- "Input file cannot be located or read" (Not all specializations are installed in the DITA-OT.)
There are more, but I'll have to go look at my notes.
