### ISSUE TITLE
Rename "combining-local-commits" to "Squashing local commits"

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#88]
I looked whether commit squashing is explained in the DITA-OT Git cheat sheet. It is called [combining-local-commits](https://github.com/dita-ot/dita-ot/wiki/Git-cheat-sheet#combining-local-commits) there. Maybe it should be renamed to "Squashing local commits", this is more common.

**Comment by jelovirt** [comment]
"Combining" is a better term for people who are new to the concept, "squashing" is better if you already know Git and rebasing/squash merging.

**Comment by infotexture** [comment]
I agree with @jelovirt, “combining” is more helpful for those less familiar with Git, and thus more suitable to the target audience of the wiki page. 

Might be worth mentioning “squashing” too though. 

Project collaborators can edit wiki pages — feel free to revise it as appropriate.

I'll close this issue here, as it is not related to the source files of the DITA-OT docs tracked in this repo.
